### ISSUE TITLE
fill doesn't work with integer64

### ISSUE THREAD

**Issue by wushuhsu** [tidyverse/tidyr#1061]
Please briefly describe your problem and what output you expect. If you have a question, please don't use this form. Instead, ask on <https://stackoverflow.com/> or <https://community.rstudio.com/>.

Please include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](https://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

---

dplyr::fil doesn't work with integer64

```r
a <- bit64::c.integer64(1, 2, NA, 3)
fill(a)
```
Error in UseMethod("fill_") : 
  no applicable method for 'fill_' applied to an object of class "integer64"

**Comment by hadley** [comment]
Can you please provide a minimal reprex (reproducible example)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please [help me help you](https://nypdecider.files.wordpress.com/2014/08/help-me-help-you.gif)! 

If you've never heard of a reprex before, start by reading "[What is a reprex](http://reprex.tidyverse.org/articles/reprex.html)", and follow the advice further down the page. Please make sure your reprex is created with the reprex package as it gives nicely formatted output and avoids a number of common pitfalls.

**Comment by zielinskipp** [comment]
@wushuhsu , the example you showed rises error as `tidyr::fill` takes data frame as first input, and then ... where you enter column names to be filled.

However using fill on int64 doesn't work and rises neither warrning nor error:
```
tibble(integer64 = bit64::c.integer64(1, 2, NA, 3)) %>% 
  tidyr::fill(integer64)

# A tibble: 4 x 1
  integer64
    <int64>
1         1
2         2
3        NA
4         3
```

R version 3.6.3 (2020-02-29)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.2 LTS
tidyr_1.1.2 

BTW  @hadley "what is a reprex" and "help me help you" are not working
