### ISSUE TITLE
names repair

### ISSUE THREAD

**Issue by ggrothendieck** [tidyverse/tidyr#1092]
There is no good option for unnamed columns in crossing. Everything gives something undesirable. You can get what you want if you write your own function but its too much work compared to how easy expand.grid is to use.  One possibility is to allow .name.repair to accept a prefix so that one could just write name.repair = "V"  or maybe it could just default to that.

```R
library(tidyr)
L <- list(0:1, 0:1, 0:1)
V <- function(x) paste0("V", seq_along(x))
crossing(!!!L, .name_repair = V)

expand.grid(L)
```

**Comment by hadley** [comment]
Reprex of underlying problem:

``` r
library(tidyr)
L <- list(0:1, 0:1, 0:1)
crossing(!!!L)
#> Error: Column names `<int>` and `<int>` must not be duplicated.
```

<sup>Created on 2021-02-17 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

Somewhat related to #1060 — there's a general question of how we should handle unnamed inputs. `name_repair` isn't a great fit for this problem.

**Comment by hadley** [comment]
The root cause here is a little different; rather than naming an unnamed list, it comes via `quos_auto_name()`'s handling of inline literals.`quos_auto_name()` is called from `dots_cols()` which is only used by `expand()`, `crossing()`, `nesting()` and `expand_grid()` so there the option to make these functions behave differently with unnamed inputs.

That said, I don't think we'd want to be inconsistent with `tibble()`:

``` r
L <- list(0:1, 0:1, 0:1)
tibble::tibble(!!!L)
#> Error: Column names `<int>` and `<int>` must not be duplicated.
```

<sup>Created on 2021-02-18 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

So maybe we need to adjust `quos_auto_name()`?

**Comment by davidskalinder** [comment]
Note that some of the current `.name_repair` settings can make things worse: 

``` r
library(tidyr)
L <- list(0:1, 2:3)
crossing(!!!L, .name_repair = "universal")
#> New names:
#> * `<int>` -> .int....1
#> * `<int>` -> .int....2
#> # A tibble: 4 x 2
#>   .int....1 .int....2
#>       <int>     <int>
#> 1         2         2
#> 2         2         3
#> 3         3         2
#> 4         3         3
```

<sup>Created on 2021-03-03 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

This happens because `quos_auto_name()` assigns the same name to each element of the unquote-spliced argument list (unlike when arguments are specified one by one):

``` r
library(rlang)

good <- quos(1:2, 3:4)
bad <- quos(!!!list(1:2, 3:4))

quos_auto_name(good)
#> <list_of<quosure>>
#> 
#> $`1:2`
#> <quosure>
#> expr: ^1:2
#> env:  global
#> 
#> $`3:4`
#> <quosure>
#> expr: ^3:4
#> env:  global

quos_auto_name(bad)
#> <list_of<quosure>>
#> 
#> $`<int>`
#> <quosure>
#> expr: ^<int: 1L, 2L>
#> env:  empty
#> 
#> $`<int>`
#> <quosure>
#> expr: ^<int: 3L, 4L>
#> env:  empty
```

<sup>Created on 2021-03-03 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

As a result, when `dots_cols()` is called with an unquote-spliced list, the [inner line of its `for` loop](https://github.com/tidyverse/tidyr/blob/2fd80d51351cef55cbd0d5ae8ddde58a8fb6be48/R/expand.R#L190) assigns the same value to *all* elements of its output each time the loop is run; and so `dots_cols()` ends up returning a bunch of copies of the last element of the unquote-spliced list argument.
