### ISSUE TITLE
`drop_na` removes empty vectors where `filter(!is.na)` does not

### ISSUE THREAD

**Issue by orgadish** [tidyverse/tidyr#1308]
In #939, `filter(across(everything(), ~is.na(.x)))` is referenced as a `dplyr` replacement to `drop_na`.

However, `drop_na` removes empty vectors where `filter(!is.na)` does not:

``` r
library(tidyverse)

all_equal(drop_na(starwars),filter(starwars, across(everything(), ~!is.na(.x))))
#> [1] "Different number of rows"

starwars_without_empty_vectors <- filter(starwars, across(everything(), ~lengths(.x) > 0))
all_equal(drop_na(starwars_without_empty_vectors),filter(starwars_without_empty_vectors, across(everything(), ~!is.na(.x))))
#> [1] TRUE
```

<sup>Created on 2022-01-30 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by DavisVaughan** [comment]
This particular issue about dropping empty vectors has been fixed in the dev version. See the last bullet in this section of the NEWS https://github.com/tidyverse/tidyr/blob/main/NEWS.md#missing-values

It isn't the same as `!is.na()` though. `drop_na()` is now backed by `vctrs::vec_equal_na()`. For lists, that only treats `NULL` elements as a missing value. i.e. an element containing a single `NA` won't be considered missing, unlike `is.na()`. I think this is odd behavior for `is.na()` because `NA` is missing but `c(NA, NA)` isn't.

``` r
library(vctrs)

# Why?
is.na(list(NA, c(NA, NA), NULL))
#> [1]  TRUE FALSE FALSE

# Only NULL is considered missing
vctrs::vec_equal_na(list(NA, c(NA, NA), NULL))
#> [1] FALSE FALSE  TRUE
```

<sup>Created on 2022-01-31 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
