### ISSUE TITLE
More informative error when `names_from` in `id_cols`

### ISSUE THREAD

**Issue by bwiernik** [tidyverse/tidyr#1324]
Related to https://github.com/tidyverse/tidyr/issues/1318

Previously, this worked:

```r
library(tidyverse)
lotr  <- read_csv("https://raw.githubusercontent.com/jennybc/lotr-tidy/master/data/lotr_tidy.csv") |> 
  rename(Species = Race)

(lotr_wide <- lotr |> 
  pivot_wider(id_cols = c(-Species, -Words), 
              names_from = Species, 
              values_from = Words))
```

But as of 1.2.0, the columns in `names_from` and `values_from` can no longer be included in `id_cols` (with or without `-`). 

In class today, this tripped up me and my students because I wasn't expecting this change, and the error message was a generic "column not found" error from tidyselect.

Would it be possible to better highlight this changed behavior for this case with a message saying `` "`id_cols` cannot contain variables included in `names_from` or `values_from`" `` or similar?

**Comment by eutwt** [comment]
The error message was improved in https://github.com/tidyverse/tidyr/pull/1321

``` r
library(tidyr)
lotr  <- readr::read_csv("https://raw.githubusercontent.com/jennybc/lotr-tidy/master/data/lotr_tidy.csv",
                         show_col_types = FALSE) |> 
  dplyr::rename(Species = Race)

(lotr_wide <- lotr |> 
  pivot_wider(id_cols = c(-Species, -Words), 
              names_from = Species, 
              values_from = Words))
#> Error in `select_wider_id_cols()` at tidyr/R/pivot-wide.R:534:2:
#> ! `id_cols` can't select a column already selected by `names_from`.
#> ℹ Column `Species` has already been selected.
```

<sup>Created on 2022-02-17 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by DavisVaughan** [comment]
Yea I've tried to improve both the error message and the documentation to be clear about the fact that the only columns available to you in `id_cols` are the ones _after_ both `names_from` and `values_from` have been removed. Otherwise you can get strange silent behavior as described in https://github.com/tidyverse/tidyr/issues/1318#issuecomment-1034095988

It is a little unfortunate here, because you really aren't trying to select `Species` and `Words` in `id_cols` (i.e. you aren't doing anything "bad"), but tidyselect errors if you use `-col` and `col` is missing from the data, which is the case here because both `Species` and `Words` have already been removed since they aren't potential `id_cols`.

Hopefully the new error message at least hints at the fact that you shouldn't be specifying anything about the `names_from` or `values_from` columns at all.
