### ISSUE TITLE
Should the `.value` placeholder be `.variable?

### ISSUE THREAD

**Issue by hadley** [tidyverse/tidyr#1326]
Take this example:

```R
family <- tribble(
  ~family,  ~dob_child1,  ~dob_child2, ~name_child1, ~name_child2,
        1, "1998-11-26", "2000-01-29",      "Susan",       "Jose",
        2, "1996-06-22",           NA,       "Mark",           NA,
        3, "2002-07-11", "2004-04-05",        "Sam",       "Seth",
        4, "2004-10-10", "2009-08-27",      "Craig",       "Khai",
        5, "2000-12-05", "2005-02-28",     "Parker",     "Gracie",
)
family <- family %>% 
  mutate(across(starts_with("dob"), parse_date))
family
```

I think it's natural to say something like: This problem is hard because the column names contain both a variable name (`dob`, `name`) and a variable value (`child1`, `child2`).  But the specification is:

```R
family %>% 
  pivot_longer(
    cols = !family, 
    names_to = c(".value", "child"), 
    names_sep = "_", 
    values_drop_na = TRUE
  )
```

Would it be easier to understand if it was:

```R
family %>% 
  pivot_longer(
    cols = !family, 
    names_to = c(".variable", "child"), 
    names_sep = "_", 
    values_drop_na = TRUE
  )
```

?

(We'd still keep `.value` for backward compatibility)

**Comment by DavisVaughan** [comment]
I think I would have said something like:

This problem is hard because the column names contain the names of the explicit variables (`dob` and `name`) along with the name and value of another implicit variable (`child`, with values `1` and `2`).

---

I'm not sure that renaming `.value` to `.variable` makes it clearer that `.variable` is referring to the explicit variables here.

There is something nice about the fact that `.value` overrides `values_to =`. That is my main hesitation about making this change. But maybe I am trying to tie those too closely together just based on the name alone.

If you feel strongly that this is the right name, then I don't feel strongly enough to disagree

**Comment by hadley** [comment]
Hmmmm, I'll think about how to rephrase my explanation to focus on `.value` overriding `values_to`.

**Comment by hadley** [comment]
Ok, I think this works:

This dataset contains data about five families, with the names and dates of birth of up to two children. The new challenge in this dataset is that the column names contain the name of two variables (`dob`, `name)` and the values of another (`child,` with values 1 and 2). We again we need to supply a vector to `names_to` but this time we use the special `".value"` sentinel. This overrides the usual `values_to` argument and keeps the first component of the column name as a variable name.
