### ISSUE TITLE
full_seq can't find a variable if it's named "d"

### ISSUE THREAD

**Issue by martina-starc** [tidyverse/tidyr#1328]
When used within `complete`, `full_seq` does not find a variable if it's called "d". ```Error in full_seq(d, 1) : object 'd' not found```. It doesn't throw an error when you rename d to something else, like "date", for example.

```r
library(tidyverse)
tibble(d = as.Date(c("2022-01-01", "2022-01-02", "2022-01-04", "2022-01-05")), v = c(3, 2, 0, 3)) %>%
    complete(d = full_seq(d, 1))
```

**Comment by DavisVaughan** [comment]
Unfortunately this comes from R's partial matching of arguments. It is matching `d` to the argument to `complete()` named `data`, which should be the data frame. Here is a minimal example:

``` r
library(tidyr)
#> Warning: package 'tidyr' was built under R version 4.1.2

df <- tibble(d = 1)

# really this is the issue
complete(df, d = 1)
#> Error in UseMethod("complete"): no applicable method for 'complete' applied to an object of class "c('double', 'numeric')"

# which is showing in a different way for you
complete(df, d = full_seq(d, 1))
#> Error in full_seq(d, 1): object 'd' not found
```

Ideally we would have named the argument `.data` rather than `data`, but it is too late for that unfortunately.

Technically you can splice in a list of expressions like this, and that will avoid the partial matching

``` r
complete(df, !!!rlang::exprs(d = full_seq(d, 1)))
#> # A tibble: 1 × 1
#>       d
#>   <dbl>
#> 1     1
```

But really it is probably just easier to give your column a different name here, sorry

**Comment by martina-starc** [comment]
I see, thanks for explaining! Renaming does seem like the best option then. :)
