### ISSUE TITLE
int64 summation fails

### ISSUE THREAD

**Issue by gui-salome** [tidyverse/tidyr#1545]
Problem: 4 + 3 + 4 = 5.43-e323
<img width="299" alt="Screenshot 2024-03-11 at 4 13 10 PM" src="https://github.com/tidyverse/tidyr/assets/68299186/b7b25ddd-2333-4c25-b267-4324fbc61568">

Reprex:
```r
tibble::tribble(
              ~ group, ~ `1`, ~ `2`, ~ `3`,
              "A", bit64::as.integer64(4), bit64::as.integer64(3), bit64::as.integer64(4)
            ) %>%
    dplyr::group_by(group) %>%
    tidyr::nest() %>% # creates 'data' column
    dplyr::mutate(
             x = purrr::map(data, function(x) {list("sum"=sum(unlist(x)))})
           ) %>%
    tidyr::unnest_wider(c(data, x))
```

**Comment by munoztd0** [comment]
The issue you're experiencing is due to the use of the base R sum function with integer64 objects from the bit64 package. The base R sum function does not handle integer64 objects correctly, which is causing the incorrect result.

You should use the bit64::sum.integer64 function instead, which is designed to correctly handle integer64 objects. Here's the corrected code:


``` r
tibble::tribble(
  ~ group, ~ `1`, ~ `2`, ~ `3`,
  "A", bit64::as.integer64(4), bit64::as.integer64(3), bit64::as.integer64(4)
) |>
  dplyr::group_by(group) |>
  tidyr::nest() |> # creates 'data' column
  dplyr::mutate(
    x = purrr::map(data, function(x) {list("sum"=bit64::sum.integer64(unlist(x)))})
  ) |>
  tidyr::unnest_wider(c(data, x))
#> # A tibble: 1 × 5
#> # Groups:   group [1]
#>   group     `1`     `2`     `3`     sum
#>   <chr> <int64> <int64> <int64> <int64>
#> 1 A           4       3       4      11
```
This should resolve the issue and give you the correct sum for your integer64 values.

**Comment by gui-salome** [comment]
@munoztd0 @hadley Thank you both for explaining the problem and solution!
