### ISSUE TITLE
Calling tidyr::unnest on a NULL causes RStudio infinite loop when in browser()

### ISSUE THREAD

**Issue by MarkEdmondson1234** [tidyverse/tidyr#311]
I have a large data.frame with a list-column in which some are NULL:

```r
test_error[59, ]
#   accountId                                accountName webProperties
#59  54853607 X - EMA - Belgium - old unused setup          NULL
```

This causes an `Error: Each column must either be a list of vectors or a list of data frames [webProperties]` error when calling the function.  

When using `browser()` within that function to debug it, I narrow it down to the above row with `NULL`, but when I use `tidyr::unnest` on only that result (to check the error) I get an unstoppable error loop needing an RStudio restart:

```r
test_error[59, ] %>% tidyr::unnest()
#Error in combine_all(args[[1]]) : 
 # no data to combine, all elements are NULL
#Error in combine_all(args[[1]]) : 
 # no data to combine, all elements are NULL
#Error in combine_all(args[[1]]) : 
 # no data to combine, all elements are NULL
# ...etc...
```

Neither browser stop or session restart stops the output scroll, if I hammer the stop it crashes RStudio.

**Comment by hadley** [comment]
Can you please provide a minimal reprex (reproducible example)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please [help me help you](https://nypdecider.files.wordpress.com/2014/08/help-me-help-you.gif)! 

If you've never heard of a reprex before, start by reading "[What is a reprex](http://reprex.tidyverse.org/articles/reprex.html)", and follow the advice further down the page. Please make sure your reprex is created with the reprex package as it gives nicely formatted output and avoids a number of common pitfalls.

**Comment by MarkEdmondson1234** [comment]
I just tried with a small example and it didn't do the same, so I'll close this until I get back to the original problem.
