### ISSUE TITLE
How do I unnest a previously nest-ed?

### ISSUE THREAD

**Issue by AndreMikulec** [tidyverse/tidyr#335]
```r
library(tibble)
library(tidyr)
```

I have this.

```r
df <- data_frame(
  x = 1:2,
  y = list(
    a = 1:3,
    b = 3:1
  )
)

> df

# A tibble: 2 x 2
      x         y
  <int>    <list>
1     1 <int [3]>
2     2 <int [3]>
````

Then, I unnest it.

``` 
> df %>% unnest(.id = "id")

# A tibble: 6 x 3
      x     y    id
  <int> <int> <chr>
1     1     1     a
2     1     2     a
3     1     3     a
4     2     3     b
5     2     2     b
6     2     1     b
```

Then, I re-nest it.

```r
> nest(df %>% unnest(.id = "id"), .id = "id")
# A tibble: 6 x 3
      x     y             data
  <int> <int>           <list>
1     1     1 <tibble [1 x 1]>
2     1     2 <tibble [1 x 1]>
3     1     3 <tibble [1 x 1]>
4     2     3 <tibble [1 x 1]>
5     2     2 <tibble [1 x 1]>
6     2     1 <tibble [1 x 1]>
```

That is not the same as the original.

```r

# A tibble: 2 x 2
      x         y
  <int>    <list>
1     1 <int [3]>
2     2 <int [3]>

```

How do I make "nest(unnest(" produce back the original?

I also try

```r
>  nest(df %>% unnest(.id = "id"), -y ,.id = "id")
# A tibble: 3 x 2
      y             data
  <int>           <list>
1     1 <tibble [2 x 2]>
2     2 <tibble [2 x 2]>
3     3 <tibble [2 x 2]>

>  nest(df %>% unnest(.id = "id"), -x ,.id = "id")
# A tibble: 2 x 2
      x             data
  <int>           <list>
1     1 <tibble [3 x 2]>
2     2 <tibble [3 x 2]>
```

Still no luck.

Thanks,
Andre Mikulec

```r
> sessionInfo()
R version 3.4.1 (2017-06-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 15063)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252
[2] LC_CTYPE=English_United States.1252
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C
[5] LC_TIME=English_United States.1252

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] tidyr_0.6.3  tibble_1.3.3

loaded via a namespace (and not attached):
 [1] compiler_3.4.1   assertthat_0.2.0 R6_2.2.2         lazyeval_0.2.0
 [5] magrittr_1.5     bindrcpp_0.2     glue_1.1.1       dplyr_0.7.2
 [9] Rcpp_0.12.12     pkgconfig_2.0.1  rlang_0.1.1      bindr_0.1
```

**Comment by colearendt** [comment]
This is probably a better question for Stack Overflow.  In any case, what seems to be causing the problem here (at least in part) is your `id` column (since it causes problems with the nesting looking the same).

Excluding the `.id` parameter gets us closer:

```r
library(tibble)                      
library(tidyr)                     
library(dplyr)                       
               
df <- data_frame(                    
x = 1:2,                             
y = list(                            
a = 1:3,                             
b = 3:1                              
)                                    
)                                    
                                        
df %>% unnest() %>% nest(y,.key=y)                                                        
#> # A tibble: 2 x 2
#>       x                y
#>   <int>           <list>
#> 1     1 <tibble [3 x 1]>
#> 2     2 <tibble [3 x 1]>
```

But in order to understand why we still do not have equality, we look at the docs for `nest`:

> There are many possible ways one could choose to nest columns inside a data frame. nest() creates a list of data frames containing all the nested variables: this seems to be the most useful form in practice.

As a result, if you are trying to look exactly the same, you are shooting for something like the following, which does a naive _un-tibble_ on the column `y`.

```r
df %>% unnest() %>% nest(y, .key=y) %>% mutate(y=lapply(y,function(d) d[[1]]))       
#> # A tibble: 2 x 2
#>       x         y
#>   <int>    <list>
#> 1     1 <int [3]>
#> 2     2 <int [3]>
```

If you insist on using the `id` column, you can still do something similar, but it is unrealistic to expect the same results since you have added a column:
```r
df %>% unnest(.id='id') %>% nest(y,.key=y) %>% mutate(y=lapply(y,function(d) d[[1]]))
#> # A tibble: 2 x 3
#>       x    id         y
#>   <int> <chr>    <list>
#> 1     1     a <int [3]>
#> 2     2     b <int [3]>
```

So it is safe to say that this behavior is by design.  Despite what their naming convention might suggest, `unnest` and `nest` are _not_ inverses, because `nest` makes the conscious decision to prefer tibbles to lists / integers / etc.  Further, `nest` defaults to nesting _all columns._ It is easy enough to work around this if you need to, but it requires a knowledge of lists (`lapply`, etc.). 

For future reference, _how_ questions are generally better suited for StackOverflow.  Typically, issues on github are bugs or feature requests or something of the like - something that requires development.  In fact - there is even a [tidyr tag](https://stackoverflow.com/questions/tagged/tidyr) on StackOverflow!

**Comment by hadley** [comment]
@colearendt thanks for the great answer!
