### ISSUE TITLE
Surprising behaviour of data expressions (symbols or functions not found)

### ISSUE THREAD

**Issue by Ks7997** [tidyverse/tidyr#350]
The following line in my script
`gather(f16means, key = var, value = p,  which(names(f16means) == "q213_1_1"):length(f16means))`
throws an error

```
 Error in which(names(f16means) == "q213_1_1") : 
     could not find function "which"
```

The same problem not only with `which`, but also with other functions from `base`.

`base` (that contains `which` function) package is installed. `extrafont` tools, `tidyr`, `dplyr`, `readxl` packages are loaded in the script. 

`tidyr` version is 0.7.0, 
R version is 3.4.1 and system is Win8.

**Comment by lionel-** [comment]
That was a deliberate change (see the NEWS file and the [blog post](http://www.tidyverse.org/articles/2017/08/tidyr-0.7.0/)), but we are going to backtrack on this since it causes too much trouble. We'll update tidyselect next week.

But it's still a good idea to follow the advice there if you're writing functions to avoid being suprised by an unexpected variable name in the data frame.

**Comment by lionel-** [comment]
You can now install the new version of `tidyselect` to get the old behaviour back:

```r
install.packages("tidyselect")
```
