### ISSUE TITLE
Warning when separate() replaces an existing column?

### ISSUE THREAD

**Issue by sharlagelfand** [tidyverse/tidyr#547]
I wonder if it would be useful to have `separate()` generate a warning or something when one of the column names in the `into` argument already exists in the data frame -- right now it just silently replaces it:

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(tidyr)

df <- tibble(str = c("1, 2, 3", "4, 5, 6"),
             x = c("a", "b"))

df
#> # A tibble: 2 x 2
#>   str     x    
#>   <chr>   <chr>
#> 1 1, 2, 3 a    
#> 2 4, 5, 6 b

df %>%
  separate(str, into = c("x", "y", "z"))
#> # A tibble: 2 x 3
#>   x     y     z    
#>   <chr> <chr> <chr>
#> 1 1     2     3    
#> 2 4     5     6
```

<sup>Created on 2019-02-06 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

<details>

<summary>Session info</summary>

``` r
devtools::session_info()
#> ─ Session info ──────────────────────────────────────────────────────────
#>  setting  value                       
#>  version  R version 3.5.2 (2018-12-20)
#>  os       macOS Sierra 10.12.1        
#>  system   x86_64, darwin15.6.0        
#>  ui       X11                         
#>  language (EN)                        
#>  collate  en_CA.UTF-8                 
#>  ctype    en_CA.UTF-8                 
#>  tz       America/Toronto             
#>  date     2019-02-06                  
#> 
#> ─ Packages ──────────────────────────────────────────────────────────────
#>  package     * version    date       lib source                          
#>  assertthat    0.2.0      2017-04-11 [1] CRAN (R 3.5.0)                  
#>  backports     1.1.3      2018-12-14 [1] CRAN (R 3.5.0)                  
#>  bindr         0.1.1      2018-03-13 [1] CRAN (R 3.5.0)                  
#>  bindrcpp      0.2.2      2018-03-29 [1] CRAN (R 3.5.0)                  
#>  callr         3.1.1      2018-12-21 [1] CRAN (R 3.5.0)                  
#>  cli           1.0.1      2018-09-25 [1] CRAN (R 3.5.0)                  
#>  crayon        1.3.4      2017-09-16 [1] CRAN (R 3.5.0)                  
#>  desc          1.2.0      2018-05-01 [1] CRAN (R 3.5.0)                  
#>  devtools      2.0.1      2018-10-26 [1] CRAN (R 3.5.2)                  
#>  digest        0.6.18     2018-10-10 [1] CRAN (R 3.5.0)                  
#>  dplyr       * 0.7.5      2018-05-19 [1] CRAN (R 3.5.2)                  
#>  evaluate      0.12       2018-10-09 [1] CRAN (R 3.5.0)                  
#>  fansi         0.4.0      2018-10-05 [1] CRAN (R 3.5.0)                  
#>  fs            1.2.6      2018-08-23 [1] CRAN (R 3.5.0)                  
#>  glue          1.3.0      2018-07-17 [1] CRAN (R 3.5.0)                  
#>  highr         0.7        2018-06-09 [1] CRAN (R 3.5.0)                  
#>  htmltools     0.3.6      2017-04-28 [1] CRAN (R 3.5.0)                  
#>  knitr         1.21       2018-12-10 [1] CRAN (R 3.5.2)                  
#>  magrittr      1.5        2014-11-22 [1] CRAN (R 3.5.0)                  
#>  memoise       1.1.0      2017-04-21 [1] CRAN (R 3.5.0)                  
#>  pillar        1.3.1      2018-12-15 [1] CRAN (R 3.5.0)                  
#>  pkgbuild      1.0.2      2018-10-16 [1] CRAN (R 3.5.0)                  
#>  pkgconfig     2.0.2      2018-08-16 [1] CRAN (R 3.5.0)                  
#>  pkgload       1.0.2      2018-10-29 [1] CRAN (R 3.5.0)                  
#>  prettyunits   1.0.2      2015-07-13 [1] CRAN (R 3.5.0)                  
#>  processx      3.2.1      2018-12-05 [1] CRAN (R 3.5.0)                  
#>  ps            1.3.0      2018-12-21 [1] CRAN (R 3.5.0)                  
#>  purrr         0.3.0.9000 2019-02-06 [1] Github (tidyverse/purrr@28a6811)
#>  R6            2.3.0      2018-10-04 [1] CRAN (R 3.5.0)                  
#>  Rcpp          1.0.0      2018-11-07 [1] CRAN (R 3.5.0)                  
#>  remotes       2.0.2      2018-10-30 [1] CRAN (R 3.5.0)                  
#>  rlang         0.3.1      2019-01-08 [1] CRAN (R 3.5.2)                  
#>  rmarkdown     1.11       2018-12-08 [1] CRAN (R 3.5.0)                  
#>  rprojroot     1.3-2      2018-01-03 [1] CRAN (R 3.5.0)                  
#>  sessioninfo   1.1.1      2018-11-05 [1] CRAN (R 3.5.0)                  
#>  stringi       1.2.4      2018-07-20 [1] CRAN (R 3.5.0)                  
#>  stringr       1.3.1      2018-05-10 [1] CRAN (R 3.5.0)                  
#>  testthat      2.0.1      2018-10-13 [1] CRAN (R 3.5.0)                  
#>  tibble        2.0.1      2019-01-12 [1] CRAN (R 3.5.2)                  
#>  tidyr       * 0.8.2.9000 2019-02-06 [1] Github (tidyverse/tidyr@0b27690)
#>  tidyselect    0.2.5      2018-10-11 [1] CRAN (R 3.5.0)                  
#>  usethis       1.4.0      2018-08-14 [1] CRAN (R 3.5.0)                  
#>  utf8          1.1.4      2018-05-24 [1] CRAN (R 3.5.0)                  
#>  withr         2.1.2      2018-03-15 [1] CRAN (R 3.5.0)                  
#>  xfun          0.4        2018-10-23 [1] CRAN (R 3.5.0)                  
#>  yaml          2.2.0      2018-07-25 [1] CRAN (R 3.5.0)                  
#> 
#> [1] /Library/Frameworks/R.framework/Versions/3.5/Resources/library
```

</details>

<br>

you can see that the original `x` column is gone.

I know that, for example, it probably doesn't make sense for something like `dplyr::mutate()` to do this, since you're often purposefully overwriting an existing column, but with `separate()` I don't think that's usually the goal. Or at least, it's not my goal, and it often bites me if I'm not careful and replace something that was already there and whose original value I needed.

**Comment by hadley** [comment]
This behaviour was introduced in tidyr 0.8.0:

* `spread()`, `separate()`, `extract()` (#255), and `gather()` (#347) now 
  replace existing variables rather than creating an invalid data frame with 
  duplicated variable names (matching the semantics of mutate).

@jennybc do you have any thoughts on what should happen here? It seems somehow related to naming conventions.

**Comment by hadley** [comment]
And code is at https://github.com/tidyverse/tidyr/commit/12ae9067c51398ce0a40e21dc51d5b55ebdb697e — looks like will only need a fix to `append_df`

**Comment by jennybc** [comment]
So far, I just contribute some analysis.

These functions all add columns and route through `append_df()`. I list as `function(arg)` where `arg` is where new variable names come from. I note whether the new names are passed explicitly or implicitly.

 * `unite(col)` *explicit*
 * `separate(into)` *explicit*
 * `extract(into)` *explicit*
 * `spread(key)` *implicit*

It's awkward to frame "(do not) overwrite an existing column" in terms of name repair. First, the inputs might be dysfunctional:

 * `data` might not have unique names (using the [tidyverse definition](https://principles.tidyverse.org/names-attribute.html#unique-names))
 * `into` might not be unique

But OK let's assume these do NOT apply, i.e. the 2 name attributes we are considering to combine are, individually, unique. Or, perhaps, if any repair is driven solely by the pre-existing `data` names or by `into`, so be it.

Note the 2 name attributes to be combined are determined *after* honoring `remove` for `extract()`, `separate()`, and `unite()` and after removing the `key` variable for `spread()`.

How to react to name overlap? Here's the second dose of awkward:

* Throw an error.  This is (sort of) `.name_repair = "check_unique`.
* Achieve unique names by overwriting. This is current behaviour.
   - How do you even frame this in terms of `.name_repair`?
* Add the new columns without overwriting, without name repair. This is
   `.name_repair = "minimal`.
* Add the new columns without overwriting, with name repair. This is
   `.name_repair = "unique`.

**Comment by hadley** [comment]
Ok, let's take pivot off the table, and move any discussion about it to #571.

That leaves us with `unite()`, `separate()` and `extract()`. These all have the property that the user explicitly supplies the new column name. As @jennybc notes, this means the issue isn't really about name repair, it's about what to do if the user supplies a column name that's already in use. (And hence has the same flavour as https://github.com/tidyverse/dplyr/issues/4230)

Currently the principle for `separate()`, `extract()`, and `unite()` is to follow what mutate does and replace existing variables. I think this is a reasonable principle because these functions are partly an accident of history — they are designed to work around the absence of a function that works like `mutate()`, but removes any existing variables used to calculate the new variables (a function we're currently calling [morph](https://github.com/tidyverse/dplyr/issues/3721).

However, as @sharlagelfand notes, this can be surprising to the analyst, so the question here is whether it's worth giving `separate()`, `extract()`, and `unite()` different behaviour — should we violate the shared principle with `mutate()` in order to make these three functions slightly less surprising? 

My sense is that it's not worth it, because the new column names are explicitly supplied. If we gave a warning, we'd also need to provide some way to turn the warning off (I personally use the current behaviour in quite a few places in the pivot vignette). It would also be a backward incompatible change (albeit minor), to a set of functions that is going to become less important as we built up more general tooling in dplyr and stringr.
