### ISSUE TITLE
Unnesting a data frame with a list column throws an error 

### ISSUE THREAD

**Issue by DanielReedOcean** [tidyverse/tidyr#658]
This issue has previously been discussed on Stackoverflow [here](https://stackoverflow.com/questions/56811233/unnesting-a-data-frame-containing-lists). I have a data frame that has a list column like below.

``` r
# Load packages
library(dplyr)
packageVersion("dplyr")
#> [1] '0.8.1'
library(tidyr)
packageVersion("tidyr")
#> [1] '0.8.3.9000'

# Create data frame
df <- structure(list(ID = 1:3, 
                     A = structure(list(c(9, 8), c(7,6), c(6, 9)), 
                                   ptype = numeric(0), 
                                   class = c("vctrs_list_of", "vctrs_vctr"))), 
                row.names = c(NA, -3L), class = c("tbl_df", "tbl", "data.frame"))

# Peek at data 
df
#> # A tibble: 3 x 2
#>      ID           A
#>   <int> <list<dbl>>
#> 1     1         [2]
#> 2     2         [2]
#> 3     3         [2]
```
I would like to flatten the list column to a regular column. I can do this with `purrr::pmap_dfr` like so giving the desired result:

```r
# Expand rows with pmap_dfr
df %>% purrr::pmap_dfr(data.frame)
#>   ID A
#> 1  1 9
#> 2  1 8
#> 3  2 7
#> 4  2 6
#> 5  3 6
#> 6  3 9
```
When I try to do the same with `unnest`, however, I receive the following error:

```r
# Expand rows with unnest
df %>% unnest(cols = A)
#> No common type for `x` <tbl_df<A:double>> and `y` <double>.
```

<sup>Created on 2019-06-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by DavisVaughan** [comment]
I think you just want `unchop()`, as the stack overflow answer suggests. `unnest()` is useful for unnesting a list column of _data frames_ (i.e. flattening what `nest()` would give you). `unchop()` is useful for flattening more generic vectors.

``` r
library(tidyr)
library(vctrs)

df <- tibble(
  ID = 1:3,
  A = as_list_of(list(c(9, 8), c(7,6), c(6, 9)))
)

df
#> # A tibble: 3 x 2
#>      ID           A
#>   <int> <list<dbl>>
#> 1     1         [2]
#> 2     2         [2]
#> 3     3         [2]

unchop(df, A)
#> # A tibble: 6 x 2
#>      ID     A
#>   <int> <dbl>
#> 1     1     9
#> 2     1     8
#> 3     2     7
#> 4     2     6
#> 5     3     6
#> 6     3     9

df2 <- tibble(
  ID = 1:3,
  A = as_list_of(list(
    tibble(x = c(9, 8)), 
    tibble(x = c(7, 6)), 
    tibble(x = c(6, 9))
  ))
)

df2
#> # A tibble: 3 x 2
#>      ID              A
#>   <int> <list<df[,1]>>
#> 1     1        [2 × 1]
#> 2     2        [2 × 1]
#> 3     3        [2 × 1]

unnest(df2, A)
#> # A tibble: 6 x 2
#>      ID     x
#>   <int> <dbl>
#> 1     1     9
#> 2     1     8
#> 3     2     7
#> 4     2     6
#> 5     3     6
#> 6     3     9
```

<sup>Created on 2019-07-02 by the [reprex package](https://reprex.tidyverse.org) (v0.2.0.9000)</sup>

**Comment by DanielReedOcean** [comment]
Thanks for the reply @DavisVaughan. So, this a deliberate change in the the functionality of `unnest` because, as noted by others on the SO post, earlier versions of `unnest` work fine?

**Comment by DavisVaughan** [comment]
Okay so I thought about this a bit more. The issue is with this line:
https://github.com/tidyverse/tidyr/blob/dc01c833a24ed3b19aa6662b018dffafa9a91177/R/nest.R#L267

Specifically the `[] <- ` assignment.

The thing that is throwing us off here is that `A` is a vctrs `list_of` object. This has strict `[<-` semantics where the RHS is cast to the type of the LHS. So when the `A` column is converted from a list of doubles to a list of data frames by `as_df()`, the `[<-.vctrs_list_of` method complains because it can't coerce that list of data frames to a list of doubles.

I think what might be needed is a new function in vctrs for this kind of operation where _you want to replace the ENTIRE column without any casting_. Maybe `vec_replace(x, value)`? It would:
- Use recycling on the RHS to match the length of the LHS
- Directly replace the LHS with the RHS without any type casting
- Be a no-op and leave the LHS intact if the RHS has size 0? This would ensure this test still passes https://github.com/tidyverse/tidyr/blob/dc01c833a24ed3b19aa6662b018dffafa9a91177/tests/testthat/test-nest.R#L186

**Comment by hadley** [comment]
Minimal reprex:

``` r
library(tidyr)
library(vctrs)

df <- tibble(
  x = 1:3,
  y = vctrs::list_of(c(9, 8), c(7,6), c(6, 9))
)


df %>% unnest(y)
#> No common type for `x` <tbl_df<y:double>> and `y` <double>.
```

<sup>Created on 2019-07-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I think this probably a bug

**Comment by hadley** [comment]
```R
# Why I am doing this?
data[[col]][] <- map(data[[col]], as_df, col = col)
# And not this?
data[[col]] <- map(data[[col]], as_df, col = col)
```

And the `map()` isn't going to work well if `data[[col]]` is a data frame.

**Comment by DavisVaughan** [comment]
I swear I tried removing the `[]` and something broke. I'll see if I can remember what that was

**Comment by DavisVaughan** [comment]
Ah, this test used to fail if you removed the `[]`, but it doesn't now that you special case the `nrow(data) == 0` case 
https://github.com/tidyverse/tidyr/blob/7a94d1cb1c3d9cfcc3c9f18220d6dd1d863413c8/tests/testthat/test-nest.R#L199
