### ISSUE TITLE
Define a default value of the cols argument of pivot_longer

### ISSUE THREAD

**Issue by atusy** [tidyverse/tidyr#661]
`pivot_longer`'s `cols` argument currently misses a default argument.
What about `everything()` because

- it is consistent to what `gather` does.
- it avoids RStudio saying "argument 'cols' is missing, with no default" when using manual spec.

![image](https://user-images.githubusercontent.com/30277794/60402763-c019df00-9bce-11e9-9601-c2db106ce77d.png)

**Comment by atusy** [comment]
Another possibility is  `cols = NULL` as a default value, and return errors if `cols` nor `spec` are specified by user.

```
iris %>% pivot_longer(NULL)
#> Error in `[[<-.data.frame`(`*tmp*`, ".value", value = "value") :  replacement has 1 row, data has 0
```

**Comment by hadley** [comment]
I like that option better; it's more inline with https://principles.tidyverse.org/def-required.html

**Comment by DavisVaughan** [comment]
I actually think it's the other way around after reading the principles. Specifically the mutually exclusive section https://principles.tidyverse.org/def-required.html#args-mutually-exclusive

It seems like both `cols` and `spec` should have no default, because you must supply one or the other (an error should be thrown if you supply both). 

However this is made more complex by the fact that the  6 `names_*` and `values_*` arguments that get passed on to `pivot_longer_spec()` should also not be allowed if `spec` is provided. That sounds like this case from the principles: "This technique should only be used for are exactly two possible arguments. If there are more than two , that is generally a sign you should create more functions."

My thought is to have an interface of:

```r
pivot_longer()
pivot_longer_spec() # manually take the spec
pivot_wider()
pivot_wider_spec()
spec_longer() # the old pivot_longer_spec()
spec_wider()
```

```r
pivot_longer <- function(data,
                         cols,
                         names_to = "name",
                         names_prefix = NULL,
                         names_sep = NULL,
                         names_pattern = NULL,
                         names_ptypes = list(),
                         values_to = "value",
                         values_drop_na = FALSE,
                         values_ptypes = list())

pivot_longer_spec <- function(data,
                              spec,
                              values_drop_na = FALSE,
                              values_ptypes = list())

# the current pivot_longer_spec() becomes:
spec_longer()
```

```r
pivot_wider <- function(data,
                        id_cols = NULL,
                        names_from = name,
                        names_prefix = "",
                        names_sep = "_",
                        values_from = value,
                        values_fill = NULL,
                        values_fn = NULL)

pivot_wider_spec <- function(data,
                             spec,
                             id_cols = NULL,
                             values_fill = NULL,
                             values_fn = NULL)

# the current pivot_wider_spec() becomes
spec_wider()
```

**Comment by hadley** [comment]
@DavisVaughan yeah, I think your analysis is correct. I don't think I like those function names, but given that you hardly ever need to use `spec` any more, I think it makes sense to pull the spec functions out.
