### ISSUE TITLE
Error when pivoting with glue strings

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [tidyverse/tidyr#676]
When using a variable that is a glue string in a pivot function,  I came across the error “Only bare vectors have shapes.” I'm not exactly sure what this error means, and it seems like something someone who is not expected to interact with vctrs might come across.

``` r
library(tidyverse)
library(glue)

df <- tibble(
  a = rep(1:2, 2), 
  b = LETTERS[1:4], 
  c = letters[1:4],
  d = c("X", "X", "Y", "Y")
  )

# works with paste -------------------------------------------------------------
df2 <- df %>%
  mutate(info = paste(b, c, sep = " - ")) %>%
  select(-b, -c) 

class(df2$info)
#> [1] "character"

df2 %>%
  pivot_wider(names_from = d, values_from = info)
#> # A tibble: 2 x 3
#>       a X     Y    
#>   <int> <chr> <chr>
#> 1     1 A - a C - c
#> 2     2 B - b D - d

# doesn't work with glue -------------------------------------------------------
df3 <- df %>%
  mutate(info = glue("{b} - {c}")) %>%
  select(-b, -c)

class(df3$info)
#> [1] "glue"      "character"

df3 %>%
  pivot_wider(names_from = d, values_from = info)
#> Only bare vectors have shapes.

# works with glue after converting to character --------------------------------
df4 <- df %>%
  mutate(info = as.character(glue("{b} - {c}"))) %>%
  select(-b, -c)

class(df4$info)
#> [1] "character"

df4 %>%
  pivot_wider(names_from = d, values_from = info)
#> # A tibble: 2 x 3
#>       a X     Y    
#>   <int> <chr> <chr>
#> 1     1 A - a C - c
#> 2     2 B - b D - d
```

<sup>Created on 2019-07-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by atusy** [comment]
The background of this error is similar to #675, #649, and https://github.com/r-lib/vctrs/issues/481.

To work around it, `vec_ptype2.glue` needs to be defined (see example below).
The problem is that which package has a responsibility to define it.

1. vctrs
2. glue
3. tidyr

`1` or `2` are plausible because `3` means every packages depending on `vctrs` and `glue` have to define variety of methods for `vec_ptype2` by themselves.

`1` was chosen in the case of the issues listed above, and the `vctrs` package defined `vec_ptype2.grouped_df`.
However, this way requires `vctrs` package to implement everytime `tidyr` or other packages depending on `vctrs` face such an error.

`3` can be a choice, but requires every package maintainer to learn `vctrs` even if they do not use it internally.

I think we need more flexible approach than `vec_ptype2` to treat arbitrary classes.

@lionel-, what do you think?

## An example of workaround

Note that this is not a good implementation.

``` r
library(tidyr)
library(dplyr, warn.conflicts = FALSE)
library(glue, warn.conflicts = FALSE)
df <- tibble(
  a = rep(1:2, 2), 
  b = LETTERS[1:4], 
  c = letters[1:4],
  d = c("X", "X", "Y", "Y")
  )

df3 <- df %>%
  mutate(info = glue("{b} - {c}")) %>%
  select(-b, -c)
vec_ptype2.glue <- function(x, y, ...) {
  UseMethod("vec_ptype2.glue", y)
}
vec_ptype2.glue.character <- function(x, y, ...) {
  character(0)
}
pivot_wider(df3, names_from = d, values_from = info)
#> # A tibble: 2 x 3
#>       a X      Y     
#>   <int> <glue> <glue>
#> 1     1 A - a  C - c 
#> 2     2 B - b  D - d
```

<sup>Created on 2019-07-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by yutannihilation** [comment]
Maybe this check is too strict? I guess an "object" (in the base-R sense) can have its shape and this seems the case.

https://github.com/r-lib/vctrs/blob/da4c2bae73e27b51b31e8eeb0420f6f8c2f7271c/R/shape.R#L81-L83

**Comment by hadley** [comment]
@atusy you should only define a method if you own the generic or the class. It's pretty clear here that it should be glue that gets the method (since we know the package author 😉). But in general, yes, I do think that the class author will need to learn a little vctrs if they want their class to work seamlessly within the tidyverse. My bet is that there's not too many classes like that, and we can personally help out where needed.

@yutannihilation yes, I'm pretty sure we're being a little bit too strict here.

**Comment by DavisVaughan** [comment]
FWIW I removed this exact restriction because it was too strict https://github.com/r-lib/rray/blob/90793f06821280b19fe02610dae0dcf73df1968c/R/shape.R#L3

**Comment by hadley** [comment]
Moved to vctrs and glue issues (see above)
