### ISSUE TITLE
extract() and separate() should have parameter ptypes

### ISSUE THREAD

**Issue by mgirlich** [tidyverse/tidyr#726]
Like `pivot_longer()` also `extract()` and `separate()` should have a parameter `ptypes`.

**Comment by hadley** [comment]
It's a slightly different case because the new variables created by `extract()` and `separate()` are always strings, so it's principle is more similar to readr's `col_types`. But this interface isn't stable yet, so unfortunately this will have to wait for a bit longer. I'm going to close this issue, because when we do come back to tackle the issue we'll look systematically across the tidyverse.
