### ISSUE TITLE
could not find function "vec_na" Error

### ISSUE THREAD

**Issue by abiyug** [tidyverse/tidyr#776]
Upgraded to tidyr 1.0.0  from 0.8.3.9000 and getting "venc_na" error on pivot_longer. Tested both CRAN and devtool versions with the same result. 

Version: tidyr_1.0.0.9000

The error
``
Error in vec_na(list(), length(values)) : 
  could not find function "vec_na"
```

REPREX
```r
df <- data.frame(id = 1:2, 
                            x = c("a","d"), 
                            y = c("b","e"),
                            z = c("c","f"))

df %>% pivot_longer(cols = x:z, names_to = "var_name", values_to = "value")
```

Here is the traceback
```
> traceback()
12: is_vector(x)
11: set_names_impl(x, x, nm, ...)
10: set_names(vec_na(list(), length(values)), names(values))
9: pivot_longer(., cols = x:z, names_to = "var_name", values_to = "value")
8: function_list[[k]](value)
7: withVisible(function_list[[k]](value))
6: freduce(value, `_function_list`)
5: `_fseq`(`_lhs`)
4: eval(quote(`_fseq`(`_lhs`)), env, env)
3: eval(quote(`_fseq`(`_lhs`)), env, env)
2: withVisible(eval(quote(`_fseq`(`_lhs`)), env, env))
1: df %>% pivot_longer(cols = x:z, names_to = "var_name", values_to = "value")
```

**Comment by cderv** [comment]
FWIW This is working as expected on my side. 

`vec_na` was a function in vctrs package that was [renamed ](https://github.com/r-lib/vctrs/blob/047c8223128d2ec6612c07df8d51af927a69884a/NEWS.md#breaking-changes) `vec_init` in vctrs 0.2.0. which version of vctrs do you have ? It may help to check and upgrade it also. However it should have been upgraded while upgrading tidyr because is it is a [dependency](https://github.com/tidyverse/tidyr/blob/e8c3f23c46025941774c269eb547cffea0ed56c2/DESCRIPTION#L40)

``` r
library(tidyr)
packageVersion("tidyr")
#> [1] '1.0.0.9000'
packageVersion("vctrs")
#> [1] '0.2.0'
df <- data.frame(id = 1:2, 
                 x = c("a","d"), 
                 y = c("b","e"),
                 z = c("c","f"))

df %>% pivot_longer(cols = x:z, names_to = "var_name", values_to = "value")
#> # A tibble: 6 x 3
#>      id var_name value
#>   <int> <chr>    <fct>
#> 1     1 x        a    
#> 2     1 y        b    
#> 3     1 z        c    
#> 4     2 x        d    
#> 5     2 y        e    
#> 6     2 z        f
```

<sup>Created on 2019-10-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

hope it helps

**Comment by abiyug** [comment]
Yes all dependencies get updated. I had a vtrs 0.2.0 version so I was not sure why the vec_na errors happened.  I went ahead and reinstalled vctrs again, and pivot_longer  starts working again.

**Comment by cderv** [comment]
Glad it works now !
