### ISSUE TITLE
Memory explosion when using pivot_wider with group_by

### ISSUE THREAD

**Issue by ifellows** [tidyverse/tidyr#897]
I've run into an issue a few times where I'll have used `group_by` on a `data.frame` at some distant point in the past. Then I'll try to reshape the data using `pivot_wider` and it will explode my whole R session resulting in me having to kill it.

I don't _believe_ that `pivot_wider` respects groupings, so I'm unclear as to why this memory issue would be expected.

```r
library(tidyr)
ff <- as.factor(1:2)
df <- expand.grid(id=as.factor(1:50), a=c("a","b","c"),b=ff, 
                  c=ff,d=ff,e=ff,f=ff,g=ff,
                  h=ff,i=ff,j=ff,
                  pos=c(TRUE,FALSE))
df$id2 <- df$id
df$id3 <- df$id
df$id4 <- df$id
df$id5 <- df$id
df$val <- rnorm(n=nrow(df))

# works
df2 <- df %>% pivot_wider(names_from=pos,values_from = val)

# blows up
df3 <-df %>% dplyr::group_by(id,id2,id3,id4,id5,
                             a,b,c,d,e,f,g,
                             h,i,j) %>% pivot_wider(names_from=pos,values_from = val)
```

```
> sessionInfo()
R version 3.5.2 (2018-12-20)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS  10.15.2

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] tidyr_1.0.0

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.3       fansi_0.4.0      utf8_1.1.4       packrat_0.5.0    zeallot_0.1.0   
 [6] crayon_1.3.4     dplyr_0.8.3      assertthat_0.2.1 R6_2.4.1         lifecycle_0.1.0 
[11] backports_1.1.5  magrittr_1.5     pillar_1.4.3     cli_2.0.0        rlang_0.4.2     
[16] rstudioapi_0.10  vctrs_0.2.1      tools_3.5.2      glue_1.3.1       purrr_0.3.3     
[21] compiler_3.5.2   pkgconfig_2.0.3  tidyselect_0.2.5 tibble_2.1.3    
```

**Comment by DavisVaughan** [comment]
Here is a minimal example of what locks up R for me. Reducing the number of id columns by at all results in something that won't crash.

This is a _massive_ number of groups to compute `expand_groups()` on (which `compute_groups(drop = FALSE)` will do), which is why it errors.

Honestly I think a good fix is to ensure we are more correctly passing the `.drop` value of the `input` all the way through in `reconstruct_tibble()`, which is what I do in #914 

```r
library(tidyr)

df <- tibble(
  id = as.factor(1:50),
  id2 = id,
  id3 = id,
  id4 = id,
  id5 = id
)

dplyr:::compute_groups(
  df, 
  c("id", "id2", "id3", "id4", "id5"), 
  drop = FALSE
)
```

**Comment by hadley** [comment]
@DavisVaughan are you implying that this issue is fixed by your PR?

**Comment by DavisVaughan** [comment]
Yea with dev tidyr and dev dplyr the original example at the top finishes almost instantly because of the change to `reconstruct_tibble()` in the PR.

My dplyr-only example above with `compute_groups()` will still lock up. I think this is mainly because it is a massive amount of groups to compute on. I don't _think_ it is a bug with the underlying C++ implementation of `compute_groups()`.
