### ISSUE TITLE
pivot_longer() pivot_wider() need examples w/ names_sep in the function reference

### ISSUE THREAD

**Issue by PathosEthosLogos** [tidyverse/tidyr#899]
For `pivot_longer` function, there are no examples of the arguments `names_sep` and `names_pattern`. The descriptions of those arguments in the documentation seem to suggest that regex is necessary, but it's not clear. On stackoverflow, it seems that there are solutions but rarely, and they never explain why those arguments work in the way they do in the answers; the documentation should do that.

It seems too important to not have examples for these arguments when they are necessary for changing multiple columns.

**Comment by batpigandme** [comment]
FWIW, there are examples of both `names_sep` and `names_pattern` in the [pivoting vignette](https://tidyr.tidyverse.org/dev/articles/pivot.html#many-variables-in-column-names). 

The last two examples in the [`pivot_longer()` function reference](https://tidyr.tidyverse.org/reference/pivot_longer.html) uses `names_pattern`, so that one seems addressed (`pivot_wider()` doesn't have a `names_pattern` parameter).
https://github.com/tidyverse/tidyr/blob/afa5e3a4b32b422641e5a4162a03d28a03341f8f/R/pivot-long.R#L91-L105

But, as you point out, there are no examples with `names_sep` in the function ref. for `pivot_*()` in the function reference. I'm going to change the issue title to reflect this more specifically so it's easier to see what needs to be done at a glance. 🙂
