### ISSUE TITLE
Drop purrr dependency

### ISSUE THREAD

**Issue by hadley** [tidyverse/tidyr#941]
Since it's only used in 3 places.  Probably need to keep it as suggested since it's so important for `hoist()`

**Comment by rjpat** [comment]
Been working through this but not sure if I have misunderstood. Been working through the imported `{purrr}` functions to transition them over to base so that `{purrr}` could be explicitly called in `hoist()` and it just be suggested.

This is the [commit](https://github.com/rjpat/tidyr/commit/6b32129b395d47e1f656ee2f68f1d1f012f17e99) with the current work, I guess just a gut check if this is the right way or if it should only be where `{purrr}` is explicitly referenced.

**Comment by hadley** [comment]
Oh I guess I missed that some purrr functions were imported. What you've done so far looks reasonable to me.

**Comment by hadley** [comment]
Given that purrr is now quite lightweight, and it's interwined throughout tidyr, I no longer think this is worth it.
