### ISSUE TITLE
Allow pivot_longer(names_to = NULL) to produce no name columns

### ISSUE THREAD

**Issue by mitchelloharawild** [tidyverse/tidyr#961]
A suggestion. Sometimes the column names provide no new/useful information as the values encode the same (or better) information. In this case, the names column is unwanted and dropped soon after the pivot.

If `names_to` can create one or more columns based on patterns, could it be extended to allow 0 columns to simplify the `pivot_longer(names_to = "junk") %>% select(-junk)` pattern?

**Comment by hadley** [comment]
Do you want to have a go at a PR? I think it's just a matter of adding another branch to `build_longer_spec()` (using `new_tibble()` to generate a tibble with 0 columns and the correct number of rows) because it already works if you create the spec yourself:

``` r
library(tidyr)

df <- data.frame(x = 1, y = 2, z = 3)

spec <- build_longer_spec(df, everything())
pivot_longer_spec(df, spec)
#> # A tibble: 3 x 2
#>   name  value
#>   <chr> <dbl>
#> 1 x         1
#> 2 y         2
#> 3 z         3

spec$name <- NULL
pivot_longer_spec(df, spec)
#> # A tibble: 3 x 1
#>   value
#>   <dbl>
#> 1     1
#> 2     2
#> 3     3
```

<sup>Created on 2020-05-15 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
